# Generated by Django 3.1.3 on 2020-11-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alumni_events_votealumni'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='story',
            field=models.TextField(default='this is how i got placed!'),
        ),
    ]
