# Generated by Django 3.1.3 on 2020-11-19 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
