# Generated by Django 3.1.6 on 2021-02-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_testimonial_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial',
            field=models.CharField(default='this is default', max_length=255),
            preserve_default=False,
        ),
    ]
